name: Build And Push

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag devopsoh/api-poi:${{ github.run_number }}
      
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: openhackq3i8na21acr 
        # Container registry password
        password: 8wUWzX4LC/shGTjxtf8lFfFAVZw3iCsP
        # Container registry server url
        login-server: openhackq3i8na21acr.azurecr.io
    
    - name: Push the Docker image
      run: docker push openhackq3i8na21acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}
        
