name: Build And Push - POI

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build apis/poi/web/ --tag openhackq3i8na21acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}
      
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
    
    - name: Push the Docker image
      run: docker push openhackq3i8na21acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: openhackq3i8na21poi
        slot-name: staging
        images: openhackq3i8na21acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}

  
  validate:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Site Health Check
      # You may pin to the exact commit or the version.
      # uses: pchalupa/site-health-check@1465433932fe6e6e51875730858e76a5d4b4df8c
      uses: pchalupa/site-health-check@v1.0.2
      with:
        # Site URL
        url: "https://openhackq3i8na21poi-staging.azurewebsites.net/api/healthcheck/poi"  
  
  swap:
    needs: validate
    runs-on: ubuntu-latest
    steps:
     - name: Azure CLI Action
       uses: Azure/cli@v1
       with:
        # Specify the script here
           inlineScript: az webapp deployment slot swap -g openhackq3i8na21rg -n openhackq3i8na21poi --slot staging --target-slot production
