name: GitHubActionsDemo

on:
# Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - apis/poi/**
  pull_request:
    branches: [ main ]
    paths:
      - apis/poi/**

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x' ]

    steps:
      - name: code checkout
        uses: actions/checkout@v2
    
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      
      - name: change workdir
        run: cd ./apis/poi

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal
